apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: web1
    env:
      # Define the environment variable
      - name: APP_USER
        valueFrom:
          configMapKeyRef:
            # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
            name: app-conf
            # Specify the key associated with the value
            key: username
      - name: FORMAT_DISK
        valueFrom:
          configMapKeyRef:
            name: app-conf
            key: execution
    envFrom: 
      - configMapRef:
          name: from-env-file
