apiVersion: v1
kind: Pod
metadata:
  labels:
    run: db-pod
  name: db-pod
spec:
  containers:
  - image: mariadb:lts
    name: db-pod
    env:
    - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
      value: "1"
