apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
  initContainers:
  - command:
    - sh
    - -c
    - sleep 30; echo init 'delay1' done
    image: busybox
    name: delay1
  - command:
    - sh
    - -c
    - sleep 5; echo init 'delay2' done
    image: busybox
    name: delay2
