apiVersion: v1
kind: Pod
metadata:
  name: multi-web
spec:
  containers:
  - image: nginx
    name: web1
  - image: httpd
    name: web2
  - command:
    - sh
    - -c
    - while true; do sleep 3600 ; done
    image: busybox
    name: busy
