apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  completions: 10
  parallelism: 5
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sh", "-c", "sleep 15"]
      restartPolicy: Never
