apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  containers:
  - image: nginx
    name: web-pod
  tolerations:
  - key: "kubernetes.io/env"
    operator: "Exists"
    effect: "NoSchedule"
