apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-pod
  name: web-pod
spec:
  initContainers:
  - name: svc-check
    image: 'radial/busyboxplus:curl'
    command: ["sh","-c","until nslookup db-svc; do echo waiting for db service to start; sleep 2; done "]
  containers:
  - image: nginx
    name: web-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
